import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://create.t3.gg/">T3 App!</a>
        </h1>
        <p>
          Get started by editing <code>src/pages/index.tsx</code>
        </p>
        <div>
          <Link href="/api/hello">
            <a>API Example</a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;

